INSERT INTO Book (id, title, author, description, genre, available, price)
    VALUES(1,'Diuna. Kroniki Diuny','Frank Herbert','Arrakis, zwana Diuną, to jedyne we wszechświecie źródło melanżu. Z rozkazu Padyszacha Imperatora planetę przejmują Atrydzi, zaciekli wrogowie władających nią dotychczas Harkonnenów. Zwycięstwo księcia Leto Atrydy jest jednak pozorne – przejęcie planety ukartowano. W odpowiedzi na atak Imperium i Harkonnenów dziedzic rodu Atrydów Paul staje na czele rdzennych mieszkańców Diuny i sięga po imperialny tron.','Fantastyka',TRUE,'41,77 zł');
INSERT INTO Book (id, title, author, description, genre, available, price)
    VALUES(2,'Wisielcza góra','Paulina Hendel','Przepraszam za wszystko – szepcze Anka, gdy czuje pętlę na szyi i patrzy w oczy brata po raz ostatni. Nigdy nie przypuszczała, że przyjazd do Grobowic sprawi, że odkryje nowy świat, obudzi duchy i stanie twarzą w twarz z prawdziwymi potworami. Antek myśli tylko o Nastce, która uciekła do mrocznego lasu. Wiej, ratuj się! Czy można jednak uciec przed demonami i przeznaczeniem? Pobyt u ciotek w odciętej od świata wiosce wydawał się idealną odskocznią od rodzinnych dramatów.','Fantastyka',true,'24,24 zł');
INSERT INTO Book (id, title, author, description, genre, available, price)
    VALUES(3,'Outsider','Stephen King','Wydaje się, że wszystko jest jasne. Wiadomo kto zabił, są na to dowody, ślady, świadkowie. Sprawa wygląda na taką, która oczywiście poraża swoim okrucieństwem, ale nie będzie sprawiała większych problemów. Czy na pewno? \"Outsider\" to wciągająca powieść Stephena Kinga, mistrza grozy i niepokoju!','Fantastyka',true,'27,86 zł');
INSERT INTO Book (id, title, author, description, genre, available, price)
    VALUES(4,'Chrzest ognia. Wiedźmin','Andrzej Sapkowski','\"Wiedźmin. Tom 5. Chrzest ognia\" to kontynuacja losów tytułowego zabójcy wampirów, kikimor i innych stworzeń czyhających na ludzkie życia. W tej części Geralt z Rivii wraz z Jaskrem nadal podąża tropem Ciri - magicznie uzdolnionej dziewczynki, z którą związany jest przeznaczeniem.','Fantastyka',false,'28,78 zł');
INSERT INTO Book (id, title, author, description, genre, available, price)
    VALUES(5,'Dom stu szeptów','Graham Masterton','Herbert Russell był naczelnikiem więzienia, który jako jedyny odważył się wykupić i zamieszkać w Allhallows Hall. Rezydencja położona na nieprzystępnych, mglistych wrzosowiskach w Dartmoor od lat uchodziła za nawiedzoną. Teraz czas Herberta minął, a posępna posiadłość odziedziczona została przez jego dzieci, z którymi od dawna był skłócony.','Horror i groza',true,'21,27 zł');
INSERT INTO Book (id, title, author, description, genre, available, price)
    VALUES(6,'Kajko i Kokosz. Szkoła latania','Janusz Christa','Pełna humoru graficzna opowieść dla prawdziwych miłośników “Kajka i Kokosza”, jednej z najsławniejszych polskich serii komiksowych o przygodach dwóch słowiańskich wojów. \"Szkoła latania\" to wspaniały album, którego nie może zabraknąć na półce z komiksami.','Komiks',true,'17,11 zł');
INSERT INTO Book (id, title, author, description, genre, available, price)
    VALUES(7,'Przepaść','Remigiusz Mróz','W Tatrach Zachodnich dochodzi do zaginięcia młodej kobiety z Warszawy. Ostatnim razem widziana była przez turystów w okolicy Trzydniowiańskiego Wierchu, a potem przepadła bez wieści. Był to jej pierwszy wyjazd w góry, miała zamiar spędzić w nich tylko weekend, a w Zakopanem pojawiła się sama – mimo to wedle ustaleń policji szła czerwonym szlakiem w towarzystwie czterech mężczyzn.','eBook',true,'31,21 zł');
